version: "3"

services:
  twitchoverlay:
    env_file: .env
    build: .
    container_name: "twitch-overlay"
    restart: always
    ports:
      - ${DOCKER_PORT}:3000
    volumes:
      - ${DATA_PATH}:/app/data
      - ${ASSETS_PATH}:/app/static
    labels:
	  - "traefik.enable=true"
	  - "traefik.http.routers.twitchoverlay.entrypoints=http"
	  - "traefik.http.routers.twitchoverlay.rule=Host(`${DATA_PATH}`)"
	  - "traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=20000000"
	  - "traefik.http.middlewares.twitchoverlay-https-redirect.redirectscheme.scheme=https"
	  - "traefik.http.routers.twitchoverlay.middlewares=twitchoverlay-https-redirect"
	  - "traefik.http.routers.twitchoverlay-secure.entrypoints=https"
	  - "traefik.http.routers.twitchoverlay-secure.rule=Host(`${DATA_PATH}`)"
	  - "traefik.http.routers.twitchoverlay-secure.tls=true"
	  - "traefik.http.routers.twitchoverlay-secure.tls.certresolver=http"
	  - "traefik.http.services.twitchoverlay.loadbalancer.server.port=${DOCKER_PORT}"
    networks:
      - proxy

networks:
  proxy:
    external: true